CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);


ALTER TABLE users
ADD COLUMN bio VARCHAR(150);

ALTER TABLE users
ADD COLUMN numOfHikes INT DEFAULT 0;

ALTER TABLE users
ADD COLUMN nameVar VARCHAR(50);