# This workflow will build and push a web application to an Azure Static Web App when you change your code.
#
# This workflow assumes you have already created the target Azure Static Web App.
# For instructions see https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_STATIC_WEB_APPS_API_TOKEN with the value of your Static Web Apps deployment token.
#    For instructions on obtaining the deployment token see: https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 3. Change the values for the APP_LOCATION, API_LOCATION and APP_ARTIFACT_LOCATION, AZURE_STATIC_WEB_APPS_API_TOKEN environment variables (below).
#    For instructions on setting up the appropriate configuration values go to https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks
# Workflow name shown in GitHub Actions
name: Azure Static Web Apps CI/CD

# Triggers: run on push to demo2 branch or manual dispatch
on:
  push:
    branches:
      - demo2          # Only fire this workflow when demo2 branch is pushed
  workflow_dispatch:   # Allow manual triggering from the Actions UI

jobs:
  build_and_deploy:    # Job identifier
    runs-on: ubuntu-latest   # Host runner image

    # Environment variables available during the build step
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}  # Inject backend URL at build time

    steps:
      # Step 1: Check out the repo without trying to fetch any submodules
      - uses: actions/checkout@v3
        with:
          submodules: false

      # Step 2: Build the React app and upload to Azure Static Web Apps
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1  # Official SWA deployment action
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Auth token for Azure
          repo_token:                                ${{ secrets.GITHUB_TOKEN }}              # GitHub token for status updates
          action:                                    upload                                 # Deploy build output
          app_location:                              Front-end                              # Folder containing your SPA source
          output_location:                           build                                 # Folder with production build artifacts
